### ISSUE TITLE
Put brightcove proxy behind fastly

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/next-brightcove-proxy-api#1]
- New URL, e.g. https://brightcove-proxy-api-next.ft.com
- vcl should live in next-brightcove-proxy-api and a little work to package up next-fastly-deploy as a script
- potentially autodeploy fastly config on pushes to master

**Comment by richard-still-ft** [comment]
Perhaps we can role this into the Fastly config for video content. I was planning on this being next-video.ft.com

**Comment by matthew-andrews** [comment]
video-next.ft.com :)

**Comment by ironsidevsquincy** [comment]
Already there - http://next-brightcove-proxy.ft.com/4084879507001

**Comment by richard-still-ft** [comment]
OK I will role into a single VCL. There is going to be a bit more complexity because there are 3 backends (at least) that we need to deal with.

**Comment by commuterjoy** [comment]
old old old
