### ISSUE TITLE
Enable "any" operator in Brightcove searches

### ISSUE THREAD

**Issue by schmodt** [Financial-Times/next-brightcove-proxy-api#22]
So that it can be used in the Brightcove search term field of this spreadsheet: https://docs.google.com/spreadsheets/d/1UTzLQPgg_POaBZeOfAQoxY5YmjKxMqdP9O9oa_Fto9s/edit#gid=0

Should improve results returned for (eg) regions - rather than "middle-east", you can search for any of Iran, Iraq, etc...

**Comment by wheresrhys** [comment]
done
